import implementation

# import cProfile
# cProfile.run('implementation.main()', sort='time')

implementation.main()

#####
##### ASCII-Art generated by http://www.ihr-freelancer.de/asciiart/
#####    Big headlines: 'Big'   Small headlines: 'Cybermedium'
##### and http://patorjk.com/software/taag/
#####    Sub-headlines: 'Small'
